apiVersion: v1
kind: Secret
metadata:
  name: {{ include "piikki-client-tg.fullname" . }}-telegram-token
  labels:
    {{- include "piikki-client-tg.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.telegram.token | b64enc | quote }}