apiVersion: v1
kind: Service
metadata:
  name: {{ include "piikki-client-tg.fullname" . }}
  labels: {{- include "piikki-client-tg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "piikki-client-tg.selectorLabels" . | nindent 4 }}
